// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcvjOW8PrMPiTNS4wU3IgyyxQtBMUjdmQ',
    appId: '1:462556531570:web:ad5bee0f68d0029d0d6beb',
    messagingSenderId: '462556531570',
    projectId: 'printair-48b71',
    authDomain: 'printair-48b71.firebaseapp.com',
    databaseURL: 'https://printair-48b71-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'printair-48b71.firebasestorage.app',
    measurementId: 'G-9N8T4LQRDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxnVpipHSIxRt4rbNk_xQUyoUwQuWTrQI',
    appId: '1:462556531570:android:9fbc67c3bcc938a70d6beb',
    messagingSenderId: '462556531570',
    projectId: 'printair-48b71',
    databaseURL: 'https://printair-48b71-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'printair-48b71.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADQ4AjdbC2jDhPrvlL1lLv2LBIbTJIgls',
    appId: '1:462556531570:web:718305e7250576990d6beb',
    messagingSenderId: '462556531570',
    projectId: 'printair-48b71',
    authDomain: 'printair-48b71.firebaseapp.com',
    databaseURL: 'https://printair-48b71-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'printair-48b71.firebasestorage.app',
    measurementId: 'G-BFFY9CK27E',
  );
}
